dotCMS/core#10400 popup menus styles
dotCMS/dotcms-dojo-theme pull request #7
Opened 2017-01-18 04:03 UTC by woontsoudev

- popup menus styles

2017-01-18 06:23 UTC, jdotcms approved these changes

2017-01-18 15:35 UTC, fmontes requested changes
All the messures in line-height or paddings etc... are varibles, needs to confirm this.

2017-01-18 21:36 UTC, jdotcms approved these changes

2017-01-18 21:52 UTC, fmontes requested changes

2017-01-18 21:52 UTC, fmontes commented on scss/backend/dot-admin/components/_context-menu.scss
> +        padding: 4px 26px;
```padding: ($basic-padding / 2) ($basic-padding * 3);```

But I don't see why we need so much left and right padding.

2017-01-18 21:52 UTC, fmontes commented on scss/backend/dot-admin/components/_context-menu.scss
> +        line-height: $menu-item-line-height;
I don't see why we need a custom line-height variable, if I'm understanding correctly we should do:

```line-height: $menu-item-height;```

2017-01-18 21:52 UTC, fmontes commented on scss/_dijit-theme-dotcms.scss
> +$menu-item-line-height: $field-height - 10;
I don't think we need this var. Also 10? where is that coming from?

2017-01-19 16:47 UTC, fmontes approved these changes

2017-01-19 17:00 UTC, merged